### PR TITLE
chore: add the git ignore file for project

### PR DESCRIPTION
**Pull request by chaoticlonghair**

### CODE REVIEW

**Comment by chaoticlonghair** [comment]
This comment was sent via GitHub API.

**Comment by yangby-cryptape** [comment]
Can one of the admins verify this patch?

**Comment by yangby-cryptape** [comment]
test this, please

**Comment by yangby-cryptape** [comment]
Test

**Comment by yangby-cryptape** [comment]
run tests

**Comment by yangby-cryptape** [comment]
run tests

**Comment by yangby-cryptape** [comment]
do test

**Comment by chaoticlonghair** [comment]
This comment was sent via GitHub API.

**Comment by chaoticlonghair** [comment]
This comment was sent via GitHub API.

**Comment by chaoticlonghair** [comment]
Test is done. -- this comment was sent via GitHub API.

**Comment by yangby-cryptape** [comment]
benchmark

**Pull request merged**
